version: '3'

services:
    node:
        image: node:13
        volumes:
            - ./app:/usr/
        tty: true
    nginx:
        build:
            context: ./nginx
            args:
                - WEB_REVERSE_PROXY_PORT=3000
        volumes:
            - ./data/logs/nginx/:/var/log/nginx
        ports:
            - 80:80
            - 443:443
        tty: true
    postgresql:
        image: postgres:12
        volumes:
            - ./data/postgresql/:/var/lib/postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
            - POSTGRES_DB=nooksh