version: "3"

services:
    nuxt:
        build: ./app
        container_name: nook.sh-website
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./app:/app
            - /app/node_modules
        command: npm run nuxt
        tty: true
        environment:
            NODE_ENV: ${NODE_ENV}


    nginx:
        image: nginx:latest
        restart: always
        container_name: nook.sh-nginx
        ports:
            - 80:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - nuxt

    db:
        image: postgres
        container_name: nook.sh-postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ./data:/var/lib/postgresql/data
