version: "3"

services:
    nuxt:
        build: ./app
        container_name: nook.sh-website
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./app:/app
            - /app/node_modules
        command: npm run dev
        tty: true
        environment:
            NODE_ENV: ${NODE_ENV}
            GITHUB_TOKEN: ${GITHUB_TOKEN}


    nginx:
        image: nginx:latest
        restart: always
        container_name: nook.sh-nginx
        ports:
            - 80:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - nuxt
